### ISSUE TITLE
Error creating the host against Katello 3.3 RC1

### ISSUE THREAD

**Issue by rarguello** [Katello/katello-client-bootstrap#149] opened 2017-01-14 03:10 UTC
Gives an error while creating the host against Katello 3.3 RC1:

```
# ./bootstrap.py -l admin -s katello.example.com -o 'Default_Organization' -L 'Default_Location' -g ServersHostGroup -a servers-ak
```

Gives this error:

```
[RUNNING], [2017-01-14 03:00:14], [Calling Foreman API to create a host entry associated with the group & org] 
An error occured: HTTP Error 500: Internal Server Error
url: https://katello.example.com:443/api/v2/hosts/
code: 500
data: {
  "host": {
    "managed": "true", 
    "name": "server1", 
    "hostgroup_id": 1, 
    "organization_id": 1, 
    "mac": "52:54:55:55:55:55", 
    "architecture_id": 1, 
    "location_id": 2, 
    "domain_id": 1
  }
}
error: {
  "error": {
    "message": "ActiveModel::ForbiddenAttributesError"
  }
}
```

Did the API change in 3.3?

**Comment by evgeni** [comment] 2017-02-23 16:39
Confirmed on katello-3.3.0-2.rc2.el7.noarch, investigating.

**Comment by evgeni** [comment] 2017-02-23 17:06
Fun, when I leave out `hostgroup_id` from the request, it works...

**Comment by evgeni** [comment] 2017-02-23 18:02
Hmm, I think this is an error regression in Foreman/Katello. What it tries to say is: your HG is not complete?!
Passing an invalid `hostgroup_id` triggers the right 404 error...

**Comment by evgeni** [comment] 2017-02-23 18:28
Mkay... Adding `"content_facet_attributes":{}` to the JSON submitted and it works with HostGroups. I don't get it.

**Comment by evgeni** [comment] 2017-02-23 18:51
Hah! This is probably related to http://projects.theforeman.org/issues/18630

Thanks @jlsherrill and @thomasmckay for listening to my ramblings in #theforman-dev :)

**Comment by evgeni** [comment] 2017-07-12 15:23
Can't reproduce with Katello 3.4.2 anymore, closing.

**Closed as completed by evgeni** 2017-07-12 15:23 UTC
