### ISSUE TITLE
Script aborts as subscription-manager does not get the subscription information immediately

### ISSUE THREAD

**Issue by wyrmiyu** [Katello/katello-client-bootstrap#193] opened 2017-06-21 08:32 UTC
While using this script to migrate hosts from Satellite 5 to Satellite 6, when the script runs the subscription-manager register it sometimes happens, especially when using VDC subscriptions, that the Satellite 6 is a bit slow to determine the subscription status.

Hence following takes place:

1. Host is registered to Satellite 6
2. Subscription-manager gets wrong subscription status and fails
3. The script bootstrap.py aborts leaving the host in-between state (registered to both Sat 5 and Sat 6)
4. Afterwards when manually running "subscription-manager status" it shows "Overall Status: Current" and the host is displayed correctly in Sat 6

Here's the script output:

```
[RUNNING], [2017-06-20 19:34:56], [/usr/sbin/subscription-manager register --org 'myorg' --name 'myhost.example.com' --activationkey 'MY-ACTIVATION-KEY'  --serverurl=https://capsule1.example.com:8443/rhsm --baseurl=https://capsule1.example.com/pulp/repos --force] 
[ERROR], [2017-06-20 19:35:11], EXITING: [/usr/sbin/subscription-manager register --org 'myorg' --name 'myhost.example.com' --activationkey 'MY-ACTIVATION-KEY'  --serverurl=https://capsule1.example.com:8443/rhsm --baseurl=https://capsule1.example.com/pulp/repos --force] failed to execute properly.
WARNING

This system has already been registered with Red Hat using RHN Classic.

Your system is being registered again using Red Hat Subscription Management. Red Hat recommends that customers only register once.

To learn how to unregister from either service please consult this Knowledge Base Article: https://access.redhat.com/kb/docs/DOC-45563
The system has been registered with ID: d064242e-420b-4425-90b7-cf54242677 

Installed Product Current Status:
Product Name: Red Hat Enterprise Linux Server
Status:       Not Subscribed

Unable to find available subscriptions for all your installed products.

```

To fix this, I propose that the [exec_failexit() on a line 305](https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L305) is changed to exec_failok and a new method is created to check subscription-manager status afterwards to determine that the registration concluded successfully. Preferably this new method would make a few attempts before raising a failure, in case Sat 6 is taking it's time.

**Comment by sideangleside** [comment] 2018-01-23 19:16
I am hesitant to implement this without having a clear reproducer. Additionally, (IMHO) it would be a little too much of 'treating the symptoms', and not the root cause

Given that:

- We set subscription-manager an urllib2 API timeouts to 900 seconds now (see #237)
- There are a number of significant registration improvements soon to be added (https://bugzilla.redhat.com/show_bug.cgi?id=1514508) 

I think this type of functionality in bootstrap.py wont be needed. @evgeni thoughts?

**Comment by evgeni** [comment] 2018-01-23 19:24
What he said ^^

No, really, we should make Satellite behave, not bootstrap work around quirks. We have enough of those for Sat5 and EL5.

**Comment by sideangleside** [comment] 2018-04-05 13:50
Closing this issue as per the above comments.

**Closed as completed by sideangleside** 2018-04-05 13:50 UTC
